"""add phone_number

Revision ID: 688e2a8ea74d
Revises: 20a667bfd191
Create Date: 2022-06-30 10:03:34.705081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688e2a8ea74d'
down_revision = '20a667bfd191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
